server:
  port: 8081
spring:
  application:
    name: "CargaMasivaCaja"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:xxx@galeras.vjcyxol.mongodb.net/banking"
  rabbitmq:
    host: possum.lmq.cloudamqp.com
    port: 5671
    username: ltqlmrty
    password: xx
    virtual-host: ltqlmrty
    ssl:
      enabled: true

app:
  fail-on-event-error: false  # o false, según el comportamiento deseado

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
